### ISSUE TITLE
Add a parameter for total consumption

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#11]
I have added the files for the new parameter I mentioned on Thuesday (total consumption as opposed to underlying consumption). This is to be treated the same way as the other customer associated files. I was not sure if adding parameters was something I could do myself or not - so to be sure I am assigning either Stuart or Patrick to do it.

**Comment by slowe** [comment]
@mary-black I've added total consumption to [the config file](https://github.com/odileeds/northern-powergrid/blob/master/data/scenarios/config.json) which sets the properties to `"totalconsumptioncf": { "title": "Total consumption with customer flexibility", "combine": "max", "units":"MW", "dp": 0 }`. I also had to rename the four files to remove the space character in the file name as that breaks on the web.

**Comment by mary-black** [comment]
Great thanks - I am about to tweak the wording in the title to "with low carbon demand technologies" rather than "with customer flexibility". I will bear in mind the file name issue next time.
