### ISSUE TITLE
Numbers on primaries have disappeared

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#12]
We noticed last week that when you click on the primary or Primary with LA view you no longer see the parameter values. We assumed you were in the middle of doing something but it is still like that so raising it as an issue just in case.

**Comment by slowe** [comment]
Good spot. That got introduced because of changing how the labels were done on the Local Authorities. I'll look at it.

**Comment by slowe** [comment]
Should be fixed. 
![Screenshot_2019-11-20 NorthernPowerGrid Future Energy Scenarios](https://user-images.githubusercontent.com/299787/69245712-3b405980-0b9f-11ea-8c2c-bfe5c57463d6.png)

**Comment by mary-black** [comment]
I had guessed it was that and told the others here that would be the answer, thank you.
