### ISSUE TITLE
Users able to raise issues

### ISSUE THREAD

**Issue by olivericketts** [odileeds/northern-powergrid#15]
Could we add a 'raise issue' link to the  visualisation to allow users to be direction to this page where they can flag any user issues? This could be under the map : "If you discover any issues with our tool, please report them **here**" ?

**Comment by slowe** [comment]
Can we re-word this so the link has meaningful text? Firstly, partially sighted people using screen readers often have links read out to them out of context so "here" doesn't explain anything. Secondly, it helps search engines know what the link is about.

So I'd suggest it just be "Please [report any issues you find](https://github.com/odileeds/northern-powergrid/issues/) with our tool".

**Comment by olivericketts** [comment]
That's fine with me!

**Comment by slowe** [comment]
Done
![Screenshot_2019-12-04 NorthernPowerGrid Future Energy Scenarios](https://user-images.githubusercontent.com/299787/70159276-8d5da080-16b0-11ea-9af6-f307ec0dd0b0.png)
