### ISSUE TITLE
Link to Datamill North Would be useful

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#16]
Can we add a link to Datamill North ready for when we go live? Or should we wait until once it is live?

**Comment by slowe** [comment]
Yes. Where do you want the link?

**Comment by mary-black** [comment]
Me and Andrew have just had a look and think the link should be to the Northern Powergrid page at Leeds ODI (from where they can then link to the data). It would probably work under the Scale section with a bold label like Data and further information:
https://odileeds.org/projects/northernpowergrid/dfes/

**Comment by slowe** [comment]
I've added some links (both under the scale and in the text at the bottom).

**Comment by mary-black** [comment]
Looks good
