### ISSUE TITLE
Can we change the parameter ordering ourselves or do you need to do that for us?

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#17]
The “Choose a parameter” list could be ordered more logically e.g. technologies with numbers (EVs, HPs) together, capacities (PV/generation) all together etc. Can we do that ourselves or do we need a quick tutorial?

**Comment by patricklake2** [comment]
If you go to the [config.json file here](https://github.com/odileeds/northern-powergrid/blob/master/data/scenarios/config.json), you can change the order of the parameters. Before you save it, run it through [JSONLint](https://jsonlint.com) to double check its valid.
