### ISSUE TITLE
We want to re-label the Absolute/Relative terms used for the switch

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#19]
We will decide shortly the new wording but want something like "Relative Scale Within Selected Year " and "Absolute Scale Across All Years". Not sure if I can do this easily myself if you point me to it, or if it lies in your territory.

**Comment by slowe** [comment]
The result will make the toggle less usable.
![Screenshot_2019-12-04 NorthernPowerGrid Future Energy Scenarios(1)](https://user-images.githubusercontent.com/299787/70159503-ed544700-16b0-11ea-9366-7d91a39b44ab.png)

There is already "hover" text that appears when you put your cursor over "Relative" and "Absolute".

**Comment by mary-black** [comment]
Ah, I meant we were looking for a form of words with those meanings. Not for them to be the actual label. It is just that our director didn't like the wording as it stands. But I take the point the wording needs to be brief. Would "In Year" and "By 2050" work? Also could we default it to the 2050 scale (the absolute one)?

**Comment by slowe** [comment]
I've changed the labels and defaulted to "absolute".

The disadvantage of defaulting to absolute is that the map looks empty for "Electric vehicles" until they change the year. If they change to "Heat pumps" (2nd parameter on the list) it also looks empty. Some people may think it is broken.

**Comment by mary-black** [comment]
Thanks for changing the wording. We take your point about defaulting to absolute (by 2050) - could you default it back to relative (in year)? We will just remember to switch it when we need to.

**Comment by slowe** [comment]
Default is now the relative (in year) scale.

**Comment by mary-black** [comment]
Thanks, great.
