### ISSUE TITLE
Add an explanation about boundary LAs

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#20]
Some Local Authorities are only partially in NPg areas, particularly in North Lincolnshire. For those, they will see a lower uptake forecasts for EVs because the model only produces forecasts for the area of their LA that overlaps with NPg, so it is not a total LA forecast. For Local Authorities that are using the tool it might help if we make clear which ones are completely in NPg and which ones have “partial forecasts”. 

Stuart/Patrick - I could mention it in the “Local authority view” section at the bottom of the page - but if you have any better ideas do let me know.

**Comment by slowe** [comment]
I think adding it in the text below works.

To make it appear somewhere else in a way that depends on what they select, we'd need to know what to say and have a way to know that a Local Authority is only "partial" e.g. would the small hole south of Ripon make Harrogate count as "partial"?

**Comment by mary-black** [comment]
Thanks. I have just added it in as a generic comment at the end of the LA view section in the html block of text underneath the map.
