### ISSUE TITLE
Add Definitions when we hover over dropdown list names

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#21]
Stuart - I am about to rename the parameters. Would the descriptions below (to right of bar) work in a hover feature and are you able to implement it? - if too long or if there is anything I can do let me know.

Parameter | Definition
Electric Vehicles (number) | Number   of registered plug in electric vehicles (pure and hybrid)
Heat Pumps (number) | Number   of heat pumps per residential household and commercial properties including   from district heating schemes
Domestic PV   installed capacity (MW) | Capacity   of solar PV panels on domestic roofs for installations less than 4kW
Large solar generation installed capacity (MW) | Installed   capacity of industrial and commercial solar farms
Wind generation installed capacity (MW) | Installed   capacity of industrial and commercial onshore and offshore wind farms
Other generation installed capacity (MW) | Installed   capacity of other generation including biomass, waste, CHP, gas, other   thermal
Energy storage installed capacity (MW) | Installed   capacity of domestic, industrial and commercial batteries
Domestic underlying energy consumption (MWh) | Annual   energy consumption by residential households excluding electric vehicle and   heat pump consumption
Industrial and commercial underlying energy consumption (MWh) | Annual   energy consumption by industrial and commercial properties excluding electric   vehicles and heat pump consumption
Total energy consumption with electric vehicles and heat pumps   (MWh) | Total   energy consumption by domestic households and industrial and commercial   properties including electric vehicle and heat pump consumption
Peak demand (MW) at Primary Substations | Peak   half hourly demand within the year
Peak demand with customer flexibility (MW) at Primary   Substations | Peak   half hourly demand within the year after load shifted by time of use tariffs   and smart charging of EVs
Peak utilisation (%) at Primary Substations | Peak   half hourly demand within the year as proportion of primary substation   capacity
Peak utilisation with customer flexibility (%) at Primary   Substations | Peak   half hourly demand within the year as proportion of primary substation   capacity after load shifted by time of use tariffs and smart charging of EVs

**Comment by slowe** [comment]
We'd previously mentioned it showing below the dropdown when you selected something (like the scenario box does). So I've assumed that is what is meant. I've added a slight grey to the background of the descriptions to subtly show they are connected to the dropdowns.

**Comment by mary-black** [comment]
Thanks that looks excellent - I will close the issue.
