### ISSUE TITLE
Change Wording in View By Dropdown List

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#22]
In the second dropdown have been asked to rename Primary Supply to Primary Substations.
Also Primary Supply  (with Local Authorities) to and Primary Substations (with Local Authorities).

Is that easy for me to do or should I pass it to Stuart or Patrick?

**Comment by patricklake2** [comment]
I've renamed both of these in commit e42b55af12e383b194a3bbf06211ff86898bda56
