### ISSUE TITLE
Set the colour scale to absolute maximum during animation

### ISSUE THREAD

**Issue by gilesdring** [odileeds/northern-powergrid#24]
I thought the animation was broken, but saw that the maximum number on the scale was changing. As a result the map appears static. Setting the scale to a maximum (based on the whole period) would show the change more clearly.

**Comment by slowe** [comment]
@gilesdring Did you see the "Colour scale" toggle?

**Comment by gilesdring** [comment]
Possibly not!

Many thanks

Giles

---
Giles Dring
Head of Delivery, ODI Leeds
07971 548826

**Comment by gilesdring** [comment]
Yep - that'll do it!
