### ISSUE TITLE
If I wanted to add parameters ...?

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#25]
I may want to add parameters during the year (like total generation). But only if it is something I can just add in using your existing structure without you having to add new code. Is it something I am able to do? If so where are the places I would need to do it?

**Comment by slowe** [comment]
@mary-black I've added some notes on adding new parameters at [https://github.com/odileeds/northern-powergrid/blob/master/data/scenarios/README.md](https://github.com/odileeds/northern-powergrid/blob/master/data/scenarios/README.md)

**Comment by mary-black** [comment]
Thanks Stuart
