### ISSUE TITLE
Some Primary-LA split amendments

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#54]
I want some LA designations added for some sites already in primaries2lad.json but blank. The most critical one is:-

GUARDIAN GLASS E06000011 : 1
NEWPORT 2 E06000011: 1

Also - Is it ok for me to update any future ones like that myself? 

Also I think there are some sites added to the tool that are possibly missing from the list, like Aycliffe Forrest? Or is it not in the tool. No matter if not as no load there yet but I was sure it was in. And did this lot get added to the shapes in the end or not?

Primary   Name
--
GUISBOROUGH T3
LEAM CENTRAL
SCARBOROUGH   66/11KV
STOBSWOOD COAL
SUNDERLAND T5   T6

**Comment by slowe** [comment]
@mary-black As you can see in the commit details above, I edited `data/primaries2lad.json` to add `GUARDIAN GLASS` and `NEWPORT 2` splits. Yes you can update this yourself. If you do you may wish to check you haven't broken the JSON file by copying the contents into https://jsonlint.com/ which will warn you if anything seems broken.

Aycliffe Forrest isn't in the `primaries2lad.json` file but is included in the shapes `data/maps/primaries-unique-all.geojson`. I don't know why.

If you look in `data/maps/primaries-unique-all.geojson` with a text editor you'll see that those 5 primaries are included.

**Comment by slowe** [comment]
Note that issues around primary to LAD splits was brought up in issue #46 so I'll close that one.

**Comment by slowe** [comment]
@mary-black to add the following to `primary2lad.json`:
  - [ ] GUISBOROUGH T3
  - [ ] LEAM CENTRAL
  - [ ] SCARBOROUGH 66/11KV
  - [ ] STOBSWOOD COAL
  - [ ] SUNDERLAND T5 T6

**Comment by slowe** [comment]
@mary-black Did this happen?

**Comment by mary-black** [comment]
Was done last year
