### ISSUE TITLE
Update Graphs Page

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#55]
I have added the csv files and amended the index file to remove unwanted graphs

**Comment by mary-black** [comment]
I have also put them in the graphs html body - but of course no sgvs generated yet

**Comment by mary-black** [comment]
Here is the spec (see Issue 56 for the two extra ones on the end)
Figure 1:Annual carbon emissions (MtCO2)
"data/graphs/Annual carbon emissions (MtCO2).csv"
			
Figure 2:Cumulative carbon emissions (MtCO2)
"data/graphs/Cumulative carbon emissions (MtCO2).csv"

Figure 3:Network annual carbon emission breakdown - Net Zero Early (MtCO2)
"data/graphs/Network annual carbon emission breakdown - Net Zero Early (MtCO2).csv"

Figure 4: Electric vehicle uptake forecast.</figcaption>
"data/graphs/Total number of EVs (#).csv"

Figure 5:Electric vehicle penetration of total car stock (%)
"data/graphs/Electric vehicle penetration of total car stock (%).csv"

Figure 6:Total number of heat pumps
"data/graphs/Total number of heat pumps (#).csv"
			
Figure 7:Battery storage capacity installed (GW)
"data/graphs/Battery storage capacity installed (GW).csv"

Figure 8:Renewable generation installed (GW)
"data/graphs/Renewable generation installed (GW).csv"

Figure 9:Annual peak demand (GW)		
"data/graphs/Annual peak demand (GW).csv"

Figure 10:Network peak demand breakdown - Net Zero Early (GW)
"data/graphs/Network annual gross peak demand breakdown - Net Zero Early (GW).csv"

Figure 11:Network energy consumption breakdown - Net Zero Early (TWh)
"data/graphs/Network energy consumption breakdown - Net Zero Early (TWh).csv"

Figure 12:Annual network energy consumption (TWh)</h3>
"data/graphs/Annual network energy consumption (TWh).csv"

Figure 13:Network annual fuel consumption breakdown - Net Zero Early (GWh-yr)
"data/graphs/Network annual fuel consumption breakdown - Net Zero Early (GWh-yr).csv"

Then two new graph breakdownd=s using the following colour codes.
Electric HGVs R255 G153 B102
Electric Buses R70 G98 B40
Electrolysers R75 G172 B198
Large industry Fuel Switching R128 G128 B128

Figure 14:Additional industrial peak demand breakdown - Net Zero Early (MW)
"data/graphs/Industry additional peak demand breakdown - Net Zero Early (MW).csv"

Figure 15: Additional industrial energy consumption breakdown - Net Zero Early (GWh)
"data/graphs/Industry additional energy consumption breakdown - Net Zero Early (GWh).csv"

**Comment by slowe** [comment]
Because of the mistakes with the hand generation I've switched to making my code generate the HTML <figure> fragments. That removes some flexibility. That means that if you edit the `graphs.html` page, but later want me to update it, your changes will be lost. The `data/graphs/index.json` file now has a "title" property for each graph and the order of the graphs in that file now matters.

**Comment by slowe** [comment]
The new colours need to be hex colours and added to `colours.csv`. I shall do that.

**Comment by slowe** [comment]
* Electric HGVs R255 G153 B102 = #FF9966
* Electric Buses R70 G98 B40 = #466228
* Electrolysers R75 G172 B198 = #4BACC6
* Large industry Fuel Switching R128 G128 B128 = #808080

**Comment by slowe** [comment]
Because of the addition of 2019 data (which wasn't there in 2020 Emerging Thinking) my code created 2010 columns so I've had to add extra error checking.

**Comment by slowe** [comment]
@mary-black Please review the graph page and see if all the changes you wanted are there.

**Comment by mary-black** [comment]
Thanks Stuart
