### ISSUE TITLE
Are Two Extra Graphs Possible

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#56]
Could we have two new graphs, each for Net Zero Early. These are along the lines of the peak demand breakdown and the energy consumption breakdown. But are for new additional loads as follows.

Colours for both graphs would be:-
Electric HGVs R255 G153 B102
Electric Buses R70 G98 B40
Electrolysers R75 G172 B198
Large industry Fuel Switching R128 G128 B128

Under Network additional peak demand breakdown heading:
Additional Peak demand breakdown
Electric HGVs
Electric Buses
Electrolysers
Large industry Fuel Switching

Under Network additional peak demand breakdown heading: 
Additional Energy consumption breakdown
Electric HGVs
Electric Buses
Electrolysers
Large industry Fuel Switching

**Comment by mary-black** [comment]
I have added tow csv files ready for these. 
Network annual additional peak demand breakdown - Net Zero Early (MW).csv
Network additional energy consumption breakdown - Net Zero Early (GWh).csv

**Comment by mary-black** [comment]
I have changed the csv file names to:-
Industry additional peak demand breakdown - Net Zero Early (MW).csv
Industry additional energy consumption breakdown - Net Zero Early (GWh).csv

**Comment by slowe** [comment]
This seems to be a repeat of part of issue #55
