### ISSUE TITLE
Update percentage allocations of primaries and local authorities

### ISSUE THREAD

**Issue by gilesdring** [odileeds/northern-powergrid#60]

**Comment by mary-black** [comment]
@nswnpg a couple to check - I will email you the details later.

**Comment by nswnpg** [comment]
Updated splits in primaries2lad.json for; Royds Lane, Durkar Low Lane, Hemsworth, Carr Lane, Hayton, Belmont Avenue, Honley, Barnsley, Morley
Did not change: Tiverton Road, Saltshouse Road
