### ISSUE TITLE
Add capacity headroom parameters

### ISSUE THREAD

**Issue by gilesdring** [odileeds/northern-powergrid#65]
Tells how many MW headroom between demand at substation and capacity of substation

There might be negative headrooms!

**Comment by mary-black** [comment]
Mary to provide the files. Stuart to think about the heat map representation.

**Comment by mary-black** [comment]
Whoops - meant to comment and leave open but closed it instead!

**Comment by slowe** [comment]
To show negative values we will want to use a diverging colour scale. We can now explicitly set this per parameter by adding `diverging: true` to the parameter definition in `config.json`. For a diverging colour scale we need a colour to use for negative values and this will need to vary per scenario. This is added as, for example, `"negativecolor": "#d7191c"` for a scenario in the `index.json` file that defines scenarios. I've added some "negative colours" to the existing scenarios based on the [diverging colour scale examples at ColorBrewer](https://colorbrewer2.org/#type=diverging&scheme=PiYG&n=5).
