### ISSUE TITLE
Add EBus and EHGV parameters

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#69]
NPg to add new parameters

**Comment by mary-black** [comment]
@nswnpg the files are dropped in now. See either directory I emailed you to for names or in 2021-DFES/data/scenarios/primaries/

eg. Number_electric_buses-CT.csv and Number_electric_HGVs-CT.csv

**Comment by nswnpg** [comment]
I have updated necessary files and it is working. I kept the 'pure and hybrid' definition (as for EVs) as a quick survey (of the DAF website) suggests that both with will be present. @mary-black let me know if this differs from the expectations you have.

**Comment by mary-black** [comment]
Thanks Neal - looks lovely. I am closing the issue.
