### ISSUE TITLE
Primary % titles in LA view

### ISSUE THREAD

**Issue by olivericketts** [odileeds/northern-powergrid#7]

**Comment by slowe** [comment]
@olivericketts I've updated the label. If you are happy with it, you can close this issue.

**Comment by slowe** [comment]
@olivericketts I've updated the label. If you are happy with it, you can close this issue.

**Comment by olivericketts** [comment]
@slowe The labels on my screen are now blank? This could just be a delay in the map updating.

**Comment by olivericketts** [comment]
Labels look good, thanks!
