### ISSUE TITLE
Postcodes for missing primaries on map

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#8]
Pass the coordinates onto @slowe

**Comment by mary-black** [comment]
Here are the postcodes for those missing primaries.


BILLET LANE | DN15 8QW
BTP | DN31 2FD
ELLIFOOT LANE | HU12 9EB
HEIGHINGTON | DL5  6JW
HUMBER ROAD | DN40 3LZ
PETERLEE INDUSTRIAL | SR8  2HR
SHEPCOTE TINSLEY | S9   1RF
STEVENSON ROAD | S9   3XG
TEES INDUSTRIAL T1 T2 | TS2 1UA
WAVERLEY BUSINESS PARK | S60  5BL

**Comment by mary-black** [comment]
Here are the rest - so we can get rid pf the warning message on the primaries view

GUARDIAN GLASS | DN14 8GA
KNOSTROP | LS9  0PJ
NEWPORT 2 | HU15 2QU
NORTH TEES T3 T4 | TS23 1PX
AYCLIFFE FORREST | DL1 3NL

**Comment by slowe** [comment]
@mary-black I've created small rectangles for each of the Primaries listed above, cut these out of the existing Primaries and then added them back e.g. "NORTH TEES T1 T2"
![Screenshot_2019-12-18 NorthernPowerGrid Future Energy Scenarios](https://user-images.githubusercontent.com/299787/71110335-ff5cdc00-21be-11ea-8fb7-004ca6520f00.png)
This should remove the yellow warning box when viewing by Primary.

**Comment by mary-black** [comment]
Thanks, nice work.

**Comment by mary-black** [comment]
Noticed Aycliffe Forrest still missing eg. on domestic PV installed capacity in the primary with LA boundaries view

**Comment by mary-black** [comment]
Hi Stuart - just wandered if you picked the last comment when I reopened the issue up ok?

**Comment by slowe** [comment]
@mary-black I'll look into it. Sorry for missing it.

**Comment by slowe** [comment]
@mary-black I think I found the problem. The view with LAs was loading the old GeoJSON file without the little rectangles.

**Comment by mary-black** [comment]
Thanks Stuart

**Comment by mary-black** [comment]
Just checked - message still there. Still says that Aycliffe Forrest is missing when you select domestic PV installed capacity in the primary with LA boundaries view. There is zero data for that new site anyway so doesn't particularly matter but it does make it look like a glitch.

**Comment by slowe** [comment]
@mary-black I've just realised the source of the problem is that the data files (e.g. [Domestic PV - Community Renewables](https://github.com/odileeds/northern-powergrid/blob/master/data/scenarios/primaries/DOMPV_MW-CommunityRenewables.csv)) have the label "AYCLIFFE FOREST" but the Primary is named "AYCLIFFE FORREST" in the GeoJSON. The different spelling (`FORREST` vs `FOREST`) means they aren't matching. Either the data files need correcting or the GeoJSON needs the name changing depending on which is the correct spelling.

**Comment by mary-black** [comment]
It should be Forrest - some of the files are wrong. Where we linked into our model it is right - but had Aycliffe Forrest manually after creation because it was only decided later we would include it. Inconsistent as I spelt it with 2 r's when I was doing it but I shared the work with others.
I will correct over time - a right pain but not a major problem.

**Comment by mary-black** [comment]
All fixed now, closing issue.
