### ISSUE TITLE
Map text appearing in white/washed-out font for some reason?

### ISSUE THREAD

**Issue by NPgMattL** [odileeds/northern-powergrid#91]
Issue with map rendering text in the wrong font colour - attempted some troubleshooting - couldn't fix.

Stuart, please could you have a look? Thanks and sorry.

**Comment by slowe** [comment]
@NPgMattL Could you add a screenshot or let me know a bit more detail as I can't see the problem? Which map rendering text? What colour? Is it for a specific scenario or all scenarios?

**Comment by slowe** [comment]
@NPgMattL Ahh. I realised it is something odd in Chrome. I've reverted to the image-based place labels.

**Comment by NPgMattL** [comment]
Ta very much @slowe - looks fixed now at a first glance =]

**Comment by mary-black** [comment]
Looks good to me. Happy new year Stuart

**Comment by slowe** [comment]
Happy new year to both of you.
