### ISSUE TITLE
SEAHAM 

### ISSUE THREAD

**Issue by mary-black** [odileeds/northern-powergrid#93]
SEAHAM 66/20 KV in your map is called SEAHAM in the csv files we are importing.

Can I just change it in the primaries lad2 json or is it more tricky than that?

**Comment by slowe** [comment]
It also needs to be updated in the GeoJSON polygons. I've also updated the repo that generates the geographies.

**Comment by mary-black** [comment]
Thanks - is there anything left that I need to update or is it all done now? In which case you can close the issue.
