### ISSUE TITLE
Data License Clarification

### ISSUE THREAD

**Issue by thisiswhereitype** [odileeds/northern-powergrid#94]
Thanks for releasing this,

Can you clarify the data license, as far as I can tell, this projects data is CC-BY judging by this [source code](https://github.com/odileeds/northern-powergrid/blob/36f09198b19b918e32d70801fd72257a49e232f1/2023-DFES/graphs.html#L249).

This appears on the bottom of the [webpage](https://odileeds.github.io/northern-powergrid/2023-DFES/):

> # [Energy scenario data](https://datamillnorth.org/)

> © Northern Powergrid & ERM 2023. Released under a Creative Commons Attribution Licence.

Please could you clarify in this repository in the readme?

**Comment by slowe** [comment]
@thisiswhereitype Hopefully that helps a bit.
